-- создание таблиц

-- таблица продуктов (сосиски)
CREATE TABLE product(
    id bigint generated by default as identity,
    name varchar(255) not null,
    picture_url varchar(255)
);

-- таблица информации о продукте 
CREATE TABLE product_info(
    product_id bigint not null,
    name varchar(255) not null, 
    price double precision
);

-- таблица заказов
CREATE TABLE orders(id bigint generated by default as identity, 
    status varchar(255)
);

-- таблица дат и статусов заказов
CREATE TABLE orders_date(
    order_id bigint not null, 
    status varchar(255), 
    date_created date default current_date
);

-- таблица связи заказов и продуктов (состав заказа)
CREATE TABLE order_product(
    quantity integer not null, 
    order_id bigint not null, 
    product_id bigint not null
);